### POST request to example server
POST http://localhost:8080/api/auth

###

### GET request to example server
GET http://localhost:8080/api/user

###

### GET request to example server
GET http://localhost:8080/api/users

###

### GET request to example server
GET http://localhost:8080

###